version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      - GITHUB_ID
      - GITHUB_SECRET
      - RAILS_SERVE_STATIC_FILES
      - RAILS_ENV
      - RAILS_LOG_TO_STDOUT
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e $RAILS_ENV"
    volumes:
      - ./app:/myapp/app
    ports:
      - "3000:3000"
    depends_on:
      - db
